### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by taghanaki** [raeyo/cv_liteflownet#1]
Hello & tnx for codes
when I run the train.py in colab + GDrive this error appears:
Traceback (most recent call last):
  File "train.py", line 59, in <module>
    os.mkdir(args.log_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/log_dir'

**Comment by raeyo** [comment]
thank you for comment

you can change the path of data root and log directory root using argument(root, log_dir)

ex) python train.py --gpu 0 --root ./MPI-Sintel --log_dir ./log_dir

so change the 'path/to/log_dir' --> 'result'

**Comment by taghanaki** [comment]
thank you, it worked but now I have a new problem!
I downloaded MPISintel dataset and ran again train.py with dataset folder for --root but this error appeared:
Traceback (most recent call last):
  File "train.py", line 72, in <module>
    train_dataset = MpiSintel(args, is_cropped=True, root=data_root, split="train")
  File "/content/drive/MyDrive/Programming/CV_Liteflownet/datasets.py", line 80, in __init__
    self.frame_size = frame_utils.read_gen(self.image_list[0][0]).shape
IndexError: list index out of range

**Comment by raeyo** [comment]
self.image_list is list of image file path of MpiSintel Image pairs. 
So self.image[0][0] means 0th image pair's first image file path
Please Check the pair of image path is properly saved to self.image_list
ex) print(self.image_list) or print(len(self.image_list))
*** 
I refer "Dataloader for MpiSintel in dataset.py" from https://github.com/NVIDIA/flownet2-pytorch
So you can also refer that repository too.

**Comment by taghanaki** [comment]
the error was from the dataset.
MPISintel dataset must have groundtruth and clean folders.
tnx again and go on!
