### ISSUE TITLE
trained model file

### ISSUE THREAD

**Issue by taghanaki** [raeyo/cv_liteflownet#2]
Hello,
I trained the net with a small dataset but the loss is big!
how can I download the best .pkl file of the trained net?

**Comment by raeyo** [comment]
Hi,
Sorry for there's no trained weight for my implementation of liteflownet.(It's not official code!) 
In my code, the loss is calculated from each cascade layers so it may be larger than official code...(but not sure)

If your goal is to use optical flow estimation by liteflownet, it would be hepful to refer to the official code.
Please see the official repository --> https://github.com/twhui/LiteFlowNet

**Comment by taghanaki** [comment]
tnx

**Comment by taghanaki** [comment]
tnx
